language: java
sudo: false # faster builds

jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
