apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canal-admin.fullname" . }}
  labels:
    {{- include "canal-admin.labels" . | nindent 4 }}
type: Opaque
data:
  application.yml: {{tpl .Values.admin.config $ | b64enc | quote }}