CREATE TABLE `tb_gcekkribdm` (
  `col_xpuntwyhls` int(253) unsigned zerofill DEFAULT NULL,
  `col_doacvjtxfj` text CHARACTER SET utf8,
  `col_vbxxcedehr` varbinary(72) DEFAULT '\0',
  `col_spnkzcnaaj` tinyint(221) unsigned zerofill DEFAULT NULL,
  `col_lctlnulyqs` varchar(141) CHARACTER SET utf8 DEFAULT '',
  `col_vdafmpnlcj` timestamp NULL DEFAULT NULL,
  `col_pwwnuhvonf` bit(1) DEFAULT NULL,
  `col_wpdnfgwkmm` float(253,19) NOT NULL,
  `col_hmbydpntpk` set('enum_or_set_0','enum_or_set_1','enum_or_set_2') CHARACTER SET utf8 DEFAULT 'enum_or_set_0',
  `col_kahmeuqzzo` mediumtext,
  `col_mrruauiuzg` mediumblob,
  `col_cxafkgwrzu` varbinary(36) DEFAULT NULL,
  `col_ooxuaiyuqa` mediumint(107) unsigned zerofill DEFAULT NULL,
  `col_mxpgmnrigf` decimal(10,0) DEFAULT NULL,
  `col_sgjbftdxrq` mediumtext CHARACTER SET utf8,
  `col_zboghrfujc` char(34) DEFAULT NULL,
  `col_xpwlcesvfx` int(73) DEFAULT NULL,
  `col_ysqvnorogf` int(10) unsigned DEFAULT '1',
  `col_dznwcqadnc` mediumtext CHARACTER SET utf8
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
