CREATE TABLE `tb_ntoztqvpgu` (
  `col_pszlqmpajg` mediumint(8) unsigned NOT NULL,
  `col_gsplwknfrh` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `col_ytfasfxidt` mediumtext CHARACTER SET utf8mb4,
  `col_guxaslfjra` set('enum_or_set_0','enum_or_set_1','enum_or_set_2') CHARACTER SET latin1 DEFAULT 'enum_or_set_0',
  `col_hzazyxoqhs` int(240) unsigned DEFAULT '1',
  `col_yrswgxnlhe` mediumtext,
  `col_bogirlzjnd` float DEFAULT NULL,
  `col_kcynrqhwrh` tinyblob,
  `col_guruxuyivx` char(1) CHARACTER SET utf8mb4 DEFAULT NULL,
  `col_aklhemsftu` datetime DEFAULT '2019-07-04 00:00:00',
  `col_bpigfcahks` longblob,
  `col_xzbtbplmxx` float(173,30) DEFAULT NULL,
  `col_abtzsnchmp` time(3) DEFAULT NULL,
  `col_xrqqlwdmuo` datetime NOT NULL,
  `col_yesjtrmdcm` smallint(5) unsigned DEFAULT '1',
  `col_szbvvxlxpk` mediumtext CHARACTER SET latin1,
  `col_qbvmzghubk` longblob,
  `col_zvbkjkirrz` mediumint(68) unsigned DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
