apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canal-server.fullname" . }}
  labels:
    {{- include "canal-server.labels" . | nindent 4 }}
type: Opaque
data:
  canal.properties: {{tpl .Values.server.config $ | b64enc | quote }}