apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "canal-server.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "canal-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
      name: tcp-admin
    - port: {{ .Values.service.ports.tcp }}
      targetPort: tcp
      protocol: TCP
      name: tcp-tcp
    - port: {{ .Values.service.ports.metric }}
      targetPort: metric
      protocol: TCP
      name: tcp-metric
  selector:
    {{- include "canal-server.selectorLabels" . | nindent 4 }}
